# Generated by Django 4.1 on 2025-04-08 02:56

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """
            db.users.updateMany({}, { $set: { "_id": ObjectId() } });
            """,
            reverse_sql="""
            db.users.updateMany({}, { $unset: { "_id": "" } });
            """
        )
    ]
