# Generated by Django 4.1 on 2025-04-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_remove_user_id_user__id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                through="octofit_tracker.TeamMember", to="octofit_tracker.user"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="octofit_tracker.team"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="octofit_tracker.user"
            ),
        ),
    ]
